input:
    audio: data/MedleyDB.lst
    onset: data/MedleyDB_onset.lst
audio:
    sr      : 22050
    duration: 20
transform_audio:
    stft_n_fft     : 512
    stft_hop_length: 256
    stft_window    : hann
    apply_hpss     : True
transform_onset:
    width_as_note  : 32
    remaining_ratio: 1.0
    includes_noise : False
    noise_mean     : 0.01
    noise_std      : 0.1
    shift_frame    : 0
    without_onset  : False
train:
    method: oinmf
model_params:
    K       : 25
    W_priors: [0.5, 1.0]        # [alpha_W, beta_W]
    H_priors: [1.1, 1.0]        # [alpha_H, beta_H]
    S_priors: [0.5, 0.99, 0.01] # [init, 1to1, 0to1]
    n_iter  : 200
    burnin  : 100
others:
    experiment_num: 10
